AllCops:
  Exclude:
    - Guardfile
    - Rakefile

AlignParameters:
  Enabled: false
BlockNesting:
  Enabled: false
BracesAroundHashParameters:
  Enabled: false
Encoding:
  Enabled: false
HashSyntax:
  Enabled: false
LineLength:
  Enabled: false
MethodLength:
  Max: 30
Documentation:
  Enabled: false
AbcSize:
  Enabled: false
CyclomaticComplexity:
  Enabled: false
ClassLength:
  Max: 1000
PerceivedComplexity:
  Enabled: false
MethodLength:
  Enabled: false
ParameterLists:
  Max: 6